pages:
  image: "pytorch/pytorch:1.2-cuda10.0-cudnn7-devel"

  tags: 
    - Kaolin

  stage: deploy

  artifacts:
    paths:
      - public
      
  only:
    - master

  before_script:
    - pip install --upgrade pip>=18.0.0
    - pip install Cython

  script:
    - nvidia-smi
    - source setenv.sh
    - python setup.py develop
    - pytest --cov=kaolin/ tests/
    - rm -rf public/
    - sphinx-build docs public/
